name: Build and Release Executable

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      QT_QPA_PLATFORM: offscreen
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --windowed run.py
      - name: Upload executable to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/run*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 